#!/usr/bin/env bun
// Refreshes the catalog snapshot bundled with Tiancode (src/marketplace/snapshot-data.ts), so
// Discover and Connections open with the current lists even offline. Run before a release:
//   bun run script/marketplace-snapshot.ts
import path from "node:path"
import { MarketplaceSources } from "../src/marketplace/sources"

const snapshot = await MarketplaceSources.fetchAll()
for (const source of snapshot.sources) console.log(`${source.ok ? "ok  " : "FAIL"} ${source.id}: ${source.count}`)
const failed = snapshot.sources.filter((source) => !source.ok)
if (failed.length > 2) throw new Error(`${failed.length} sources failed; keeping the previous snapshot`)
const counts = { mcp: 0, plugin: 0, skill: 0 }
for (const item of snapshot.items) counts[item.type]++
console.log(`items: ${snapshot.items.length}`, counts, `connectors: ${snapshot.connectors.length}`)
// The community marketplace (2,000+ plugins, two thirds of the size) arrives with the first online
// refresh; the bundled copy keeps the curated sources and shorter descriptions.
const bundled = {
  ...snapshot,
  items: snapshot.items
    .filter((item) => item.source !== "claude-community")
    .map((item) => ({ ...item, description: item.description.slice(0, 280) })),
}
const file = path.join(import.meta.dir, "../src/marketplace/snapshot-data.ts")
await Bun.write(
  file,
  `// Generated by script/marketplace-snapshot.ts on ${new Date(snapshot.fetchedAt).toISOString()}. Do not edit.\nexport default ${JSON.stringify(JSON.stringify(bundled))}\n`,
)
console.log(`wrote ${file}`)
